package com.example.notesapp.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLightMediumContrast = Color(0xFF287975)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF24817D)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF2E4745)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF607977)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF2D455E)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF5F7792)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF4FBF9)
val onBackgroundLightMediumContrast = Color(0xFF161D1C)
val surfaceLightMediumContrast = Color(0xFFF4FBF9)
val onSurfaceLightMediumContrast = Color(0xFF0D2526)
val surfaceVariantLightMediumContrast = Color(0xFFDAE5E3)
val onSurfaceVariantLightMediumContrast = Color(0xFF3B4544)
val outlineLightMediumContrast = Color(0xFF576160)
val outlineVariantLightMediumContrast = Color(0xFF737D7B)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2B3231)
val inverseOnSurfaceLightMediumContrast = Color(0xFFECF2F0)
val inversePrimaryLightMediumContrast = Color(0xFF80D5CF)
val surfaceDimLightMediumContrast = Color(0xFFD5DBDA)
val surfaceBrightLightMediumContrast = Color(0xFFF4FBF9)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFEFF5F3)
val surfaceContainerLightMediumContrast = Color(0xFFE9EFEE)
val surfaceContainerHighLightMediumContrast = Color(0xFFE3E9E8)
val surfaceContainerHighestLightMediumContrast = Color(0xFFDDE4E2)


val primaryDarkMediumContrast = Color(0xFF85D9D4)
val onPrimaryDarkMediumContrast = Color(0xFF001A19)
val primaryContainerDarkMediumContrast = Color(0xFF489E99)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFB5D0CD)
val onSecondaryDarkMediumContrast = Color(0xFF011A19)
val secondaryContainerDarkMediumContrast = Color(0xFF7B9693)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFB5CDEC)
val onTertiaryDarkMediumContrast = Color(0xFF00172C)
val tertiaryContainerDarkMediumContrast = Color(0xFF7B93B0)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0E1514)
val onBackgroundDarkMediumContrast = Color(0xFFDDE4E2)
val surfaceDarkMediumContrast = Color(0xFF0E1514)
val onSurfaceDarkMediumContrast = Color(0xFFF6FCFA)
val surfaceVariantDarkMediumContrast = Color(0xFF3F4948)
val onSurfaceVariantDarkMediumContrast = Color(0xFFC2CDCB)
val outlineDarkMediumContrast = Color(0xFF9BA5A3)
val outlineVariantDarkMediumContrast = Color(0xFF7B8584)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDDE4E2)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF252B2B)
val inversePrimaryDarkMediumContrast = Color(0xFF00514E)
val surfaceDimDarkMediumContrast = Color(0xFF0E1514)
val surfaceBrightDarkMediumContrast = Color(0xFF343A3A)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF090F0F)
val surfaceContainerLowDarkMediumContrast = Color(0xFF161D1C)
val surfaceContainerDarkMediumContrast = Color(0xFF1A2120)
val surfaceContainerHighDarkMediumContrast = Color(0xFF252B2B)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF2F3635)

val lighterGreen= Color(0xFF7ACEC4)
